feat: show hostname of running app
arcjet/example-nextjs pull request #171
Opened 2024-11-05 15:09 UTC by e-moran

Currently we just hardcode the shield cURL request to hit `example.arcjet.com`.
Instead we should attempt to resolve the hostname that the user is using so that they
hit their own app and it shows up in their logs.

2024-11-05 22:11 UTC, blaine-arcjet approved these changes
It's cool that this can be tested via the deploy preview:
<img width="1347" alt="Screenshot 2024-11-05 at 5 10 29 PM" src="https://github.com/user-attachments/assets/b5651f22-3776-438b-9695-9b867c132cb8">

2024-11-05 22:28 UTC, davidmytton commented
Don't forget to add this to https://github.com/arcjet/example-nextjs-fly as well

2024-11-08 16:20 UTC, davidmytton requested changes
We'll merge this alongside adding this to the Fly app example as well, so drop the PR link in here when it's done.

2024-11-08 20:19 UTC, e-moran commented
> We'll merge this alongside adding this to the Fly app example as well, so drop the PR link in here when it's done.

https://github.com/arcjet/example-nextjs-fly/pull/122

2024-11-08 20:35 UTC, merged